services:
  - type: web
    name: vitor-cachoeira-portfolio-2026
    runtime: static
    rootDir: portfolio
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

